version: "3.2"
services:
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - ${REDIS_PORT}:6379
    api:
        image: node:latest
        container_name: api
        restart: always
        depends_on:
            - redis
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: NODE_ENV=production npm start
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
